{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [],
   "source": [
    "os.mkdir('.kaggle')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting kaggle\n",
      "  Using cached kaggle-1.5.16-py3-none-any.whl\n",
      "Requirement already satisfied: six>=1.10 in c:\\users\\16695\\anaconda3\\envs\\titanic\\lib\\site-packages (from kaggle) (1.16.0)\n",
      "Collecting certifi (from kaggle)\n",
      "  Obtaining dependency information for certifi from https://files.pythonhosted.org/packages/4c/dd/2234eab22353ffc7d94e8d13177aaa050113286e93e7b40eae01fbf7c3d9/certifi-2023.7.22-py3-none-any.whl.metadata\n",
      "  Using cached certifi-2023.7.22-py3-none-any.whl.metadata (2.2 kB)\n",
      "Requirement already satisfied: python-dateutil in c:\\users\\16695\\anaconda3\\envs\\titanic\\lib\\site-packages (from kaggle) (2.8.2)\n",
      "Collecting requests (from kaggle)\n",
      "  Obtaining dependency information for requests from https://files.pythonhosted.org/packages/70/8e/0e2d847013cb52cd35b38c009bb167a1a26b2ce6cd6965bf26b47bc0bf44/requests-2.31.0-py3-none-any.whl.metadata\n",
      "  Using cached requests-2.31.0-py3-none-any.whl.metadata (4.6 kB)\n",
      "Collecting tqdm (from kaggle)\n",
      "  Obtaining dependency information for tqdm from https://files.pythonhosted.org/packages/00/e5/f12a80907d0884e6dff9c16d0c0114d81b8cd07dc3ae54c5e962cc83037e/tqdm-4.66.1-py3-none-any.whl.metadata\n",
      "  Using cached tqdm-4.66.1-py3-none-any.whl.metadata (57 kB)\n",
      "Collecting python-slugify (from kaggle)\n",
      "  Using cached python_slugify-8.0.1-py2.py3-none-any.whl (9.7 kB)\n",
      "Collecting urllib3 (from kaggle)\n",
      "  Obtaining dependency information for urllib3 from https://files.pythonhosted.org/packages/26/40/9957270221b6d3e9a3b92fdfba80dd5c9661ff45a664b47edd5d00f707f5/urllib3-2.0.6-py3-none-any.whl.metadata\n",
      "  Downloading urllib3-2.0.6-py3-none-any.whl.metadata (6.6 kB)\n",
      "Collecting bleach (from kaggle)\n",
      "  Using cached bleach-6.0.0-py3-none-any.whl (162 kB)\n",
      "Collecting webencodings (from bleach->kaggle)\n",
      "  Using cached webencodings-0.5.1-py2.py3-none-any.whl (11 kB)\n",
      "Collecting text-unidecode>=1.3 (from python-slugify->kaggle)\n",
      "  Using cached text_unidecode-1.3-py2.py3-none-any.whl (78 kB)\n",
      "Collecting charset-normalizer<4,>=2 (from requests->kaggle)\n",
      "  Obtaining dependency information for charset-normalizer<4,>=2 from https://files.pythonhosted.org/packages/09/b8/cf771dcdfe62453b5e59b05b85ab261df1da60b1bc10c7f260b468c62426/charset_normalizer-3.3.0-cp310-cp310-win_amd64.whl.metadata\n",
      "  Using cached charset_normalizer-3.3.0-cp310-cp310-win_amd64.whl.metadata (33 kB)\n",
      "Collecting idna<4,>=2.5 (from requests->kaggle)\n",
      "  Using cached idna-3.4-py3-none-any.whl (61 kB)\n",
      "Requirement already satisfied: colorama in c:\\users\\16695\\anaconda3\\envs\\titanic\\lib\\site-packages (from tqdm->kaggle) (0.4.6)\n",
      "Using cached certifi-2023.7.22-py3-none-any.whl (158 kB)\n",
      "Using cached requests-2.31.0-py3-none-any.whl (62 kB)\n",
      "Downloading urllib3-2.0.6-py3-none-any.whl (123 kB)\n",
      "   ---------------------------------------- 0.0/123.8 kB ? eta -:--:--\n",
      "   ---------------------------------------- 123.8/123.8 kB 7.1 MB/s eta 0:00:00\n",
      "Using cached tqdm-4.66.1-py3-none-any.whl (78 kB)\n",
      "Using cached charset_normalizer-3.3.0-cp310-cp310-win_amd64.whl (98 kB)\n",
      "Installing collected packages: webencodings, text-unidecode, urllib3, tqdm, python-slugify, idna, charset-normalizer, certifi, bleach, requests, kaggle\n",
      "Successfully installed bleach-6.0.0 certifi-2023.7.22 charset-normalizer-3.3.0 idna-3.4 kaggle-1.5.16 python-slugify-8.0.1 requests-2.31.0 text-unidecode-1.3 tqdm-4.66.1 urllib3-2.0.6 webencodings-0.5.1\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "%pip install kaggle"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Downloading titanic.zip to c:\\Users\\16695\\Titanic_Kaggle_Competition\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "  0%|          | 0.00/34.1k [00:00<?, ?B/s]\n",
      "100%|██████████| 34.1k/34.1k [00:00<00:00, 540kB/s]\n"
     ]
    }
   ],
   "source": [
    "!kaggle competitions download -c titanic"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# EDA"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting pandas\n",
      "  Obtaining dependency information for pandas from https://files.pythonhosted.org/packages/ce/cd/a7c2cbffe2afff975349e60b14b63a448162145a7acac8ba12ddc2ed78a8/pandas-2.1.1-cp310-cp310-win_amd64.whl.metadata\n",
      "  Using cached pandas-2.1.1-cp310-cp310-win_amd64.whl.metadata (18 kB)\n",
      "Collecting numpy>=1.22.4 (from pandas)\n",
      "  Obtaining dependency information for numpy>=1.22.4 from https://files.pythonhosted.org/packages/cc/05/ef9fc04adda45d537619ea956bc33489f50a46badc949c4280d8309185ec/numpy-1.26.0-cp310-cp310-win_amd64.whl.metadata\n",
      "  Using cached numpy-1.26.0-cp310-cp310-win_amd64.whl.metadata (61 kB)\n",
      "Requirement already satisfied: python-dateutil>=2.8.2 in c:\\users\\16695\\anaconda3\\envs\\titanic\\lib\\site-packages (from pandas) (2.8.2)\n",
      "Collecting pytz>=2020.1 (from pandas)\n",
      "  Obtaining dependency information for pytz>=2020.1 from https://files.pythonhosted.org/packages/32/4d/aaf7eff5deb402fd9a24a1449a8119f00d74ae9c2efa79f8ef9994261fc2/pytz-2023.3.post1-py2.py3-none-any.whl.metadata\n",
      "  Using cached pytz-2023.3.post1-py2.py3-none-any.whl.metadata (22 kB)\n",
      "Collecting tzdata>=2022.1 (from pandas)\n",
      "  Using cached tzdata-2023.3-py2.py3-none-any.whl (341 kB)\n",
      "Requirement already satisfied: six>=1.5 in c:\\users\\16695\\anaconda3\\envs\\titanic\\lib\\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)\n",
      "Using cached pandas-2.1.1-cp310-cp310-win_amd64.whl (10.7 MB)\n",
      "Using cached numpy-1.26.0-cp310-cp310-win_amd64.whl (15.8 MB)\n",
      "Using cached pytz-2023.3.post1-py2.py3-none-any.whl (502 kB)\n",
      "Installing collected packages: pytz, tzdata, numpy, pandas\n",
      "Successfully installed numpy-1.26.0 pandas-2.1.1 pytz-2023.3.post1 tzdata-2023.3\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "%pip install pandas\n",
    "import pandas as pd\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "df = pd.read_csv('train.csv')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<class 'pandas.core.frame.DataFrame'>\n",
      "RangeIndex: 891 entries, 0 to 890\n",
      "Data columns (total 12 columns):\n",
      " #   Column       Non-Null Count  Dtype  \n",
      "---  ------       --------------  -----  \n",
      " 0   PassengerId  891 non-null    int64  \n",
      " 1   Survived     891 non-null    int64  \n",
      " 2   Pclass       891 non-null    int64  \n",
      " 3   Name         891 non-null    object \n",
      " 4   Sex          891 non-null    object \n",
      " 5   Age          714 non-null    float64\n",
      " 6   SibSp        891 non-null    int64  \n",
      " 7   Parch        891 non-null    int64  \n",
      " 8   Ticket       891 non-null    object \n",
      " 9   Fare         891 non-null    float64\n",
      " 10  Cabin        204 non-null    object \n",
      " 11  Embarked     889 non-null    object \n",
      "dtypes: float64(2), int64(5), object(5)\n",
      "memory usage: 83.7+ KB\n"
     ]
    }
   ],
   "source": [
    "df.info()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: pandas-profiling==3.6.6 in c:\\users\\16695\\anaconda3\\envs\\titanic\\lib\\site-packages (3.6.6)\n",
      "Collecting pandas==1.3.3\n",
      "  Downloading pandas-1.3.3.tar.gz (4.7 MB)\n",
      "     ---------------------------------------- 0.0/4.7 MB ? eta -:--:--\n",
      "     - -------------------------------------- 0.2/4.7 MB 5.9 MB/s eta 0:00:01\n",
      "     ----- ---------------------------------- 0.6/4.7 MB 7.7 MB/s eta 0:00:01\n",
      "     --------- ------------------------------ 1.1/4.7 MB 9.1 MB/s eta 0:00:01\n",
      "     -------------- ------------------------- 1.7/4.7 MB 9.7 MB/s eta 0:00:01\n",
      "     ------------------ --------------------- 2.2/4.7 MB 10.1 MB/s eta 0:00:01\n",
      "     ----------------------- ---------------- 2.8/4.7 MB 10.4 MB/s eta 0:00:01\n",
      "     -------------------------- ------------- 3.1/4.7 MB 10.0 MB/s eta 0:00:01\n",
      "     ----------------------------- ---------- 3.5/4.7 MB 10.2 MB/s eta 0:00:01\n",
      "     ---------------------------------- ----- 4.1/4.7 MB 10.4 MB/s eta 0:00:01\n",
      "     ---------------------------------------  4.6/4.7 MB 10.2 MB/s eta 0:00:01\n",
      "     ---------------------------------------- 4.7/4.7 MB 10.1 MB/s eta 0:00:00\n",
      "  Installing build dependencies: started\n",
      "  Installing build dependencies: finished with status 'error'\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "  error: subprocess-exited-with-error\n",
      "  \n",
      "  × pip subprocess to install build dependencies did not run successfully.\n",
      "  │ exit code: 1\n",
      "  ╰─> [268 lines of output]\n",
      "      Ignoring numpy: markers 'python_version == \"3.7\" and (platform_machine != \"arm64\" or platform_system != \"Darwin\") and platform_machine != \"aarch64\"' don't match your environment\n",
      "      Ignoring numpy: markers 'python_version == \"3.8\" and (platform_machine != \"arm64\" or platform_system != \"Darwin\") and platform_machine != \"aarch64\"' don't match your environment\n",
      "      Ignoring numpy: markers 'python_version == \"3.7\" and platform_machine == \"aarch64\"' don't match your environment\n",
      "      Ignoring numpy: markers 'python_version == \"3.8\" and platform_machine == \"aarch64\"' don't match your environment\n",
      "      Ignoring numpy: markers 'python_version == \"3.8\" and platform_machine == \"arm64\" and platform_system == \"Darwin\"' don't match your environment\n",
      "      Ignoring numpy: markers 'python_version == \"3.9\" and platform_machine == \"arm64\" and platform_system == \"Darwin\"' don't match your environment\n",
      "      Collecting setuptools>=51.0.0\n",
      "        Obtaining dependency information for setuptools>=51.0.0 from https://files.pythonhosted.org/packages/bb/26/7945080113158354380a12ce26873dd6c1ebd88d47f5bc24e2c5bb38c16a/setuptools-68.2.2-py3-none-any.whl.metadata\n",
      "        Downloading setuptools-68.2.2-py3-none-any.whl.metadata (6.3 kB)\n",
      "      Collecting wheel\n",
      "        Obtaining dependency information for wheel from https://files.pythonhosted.org/packages/b8/8b/31273bf66016be6ad22bb7345c37ff350276cfd46e389a0c2ac5da9d9073/wheel-0.41.2-py3-none-any.whl.metadata\n",
      "        Downloading wheel-0.41.2-py3-none-any.whl.metadata (2.2 kB)\n",
      "      Collecting Cython<3,>=0.29.21\n",
      "        Obtaining dependency information for Cython<3,>=0.29.21 from https://files.pythonhosted.org/packages/3f/d6/9eed523aeaca42acbaa3e6d3850edae780dc7f8da9df1bf6a2ceb851839c/Cython-0.29.36-py2.py3-none-any.whl.metadata\n",
      "        Downloading Cython-0.29.36-py2.py3-none-any.whl.metadata (3.1 kB)\n",
      "      Collecting numpy==1.19.3\n",
      "        Downloading numpy-1.19.3.zip (7.3 MB)\n",
      "           ---------------------------------------- 0.0/7.3 MB ? eta -:--:--\n",
      "           - -------------------------------------- 0.3/7.3 MB 8.3 MB/s eta 0:00:01\n",
      "           --- ------------------------------------ 0.7/7.3 MB 8.5 MB/s eta 0:00:01\n",
      "           ------ --------------------------------- 1.1/7.3 MB 8.9 MB/s eta 0:00:01\n",
      "           ------- -------------------------------- 1.4/7.3 MB 8.0 MB/s eta 0:00:01\n",
      "           --------- ------------------------------ 1.8/7.3 MB 8.3 MB/s eta 0:00:01\n",
      "           ------------ --------------------------- 2.2/7.3 MB 8.4 MB/s eta 0:00:01\n",
      "           -------------- ------------------------- 2.6/7.3 MB 8.3 MB/s eta 0:00:01\n",
      "           ---------------- ----------------------- 3.0/7.3 MB 8.4 MB/s eta 0:00:01\n",
      "           ------------------ --------------------- 3.4/7.3 MB 8.4 MB/s eta 0:00:01\n",
      "           --------------------- ------------------ 3.9/7.3 MB 8.7 MB/s eta 0:00:01\n",
      "           ------------------------ --------------- 4.5/7.3 MB 9.0 MB/s eta 0:00:01\n",
      "           -------------------------- ------------- 4.9/7.3 MB 9.0 MB/s eta 0:00:01\n",
      "           ----------------------------- ---------- 5.4/7.3 MB 9.2 MB/s eta 0:00:01\n",
      "           ------------------------------- -------- 5.7/7.3 MB 9.1 MB/s eta 0:00:01\n",
      "           --------------------------------- ------ 6.2/7.3 MB 9.0 MB/s eta 0:00:01\n",
      "           ------------------------------------ --- 6.7/7.3 MB 9.3 MB/s eta 0:00:01\n",
      "           ------------------------------------- -- 6.9/7.3 MB 8.9 MB/s eta 0:00:01\n",
      "           ---------------------------------------  7.3/7.3 MB 9.2 MB/s eta 0:00:01\n",
      "           ---------------------------------------- 7.3/7.3 MB 8.8 MB/s eta 0:00:00\n",
      "        Installing build dependencies: started\n",
      "        Installing build dependencies: finished with status 'done'\n",
      "        Getting requirements to build wheel: started\n",
      "        Getting requirements to build wheel: finished with status 'done'\n",
      "        Preparing metadata (pyproject.toml): started\n",
      "        Preparing metadata (pyproject.toml): finished with status 'error'\n",
      "        error: subprocess-exited-with-error\n",
      "      \n",
      "        × Preparing metadata (pyproject.toml) did not run successfully.\n",
      "        │ exit code: 1\n",
      "        ╰─> [210 lines of output]\n",
      "            setup.py:67: RuntimeWarning: NumPy 1.19.3 may not yet support Python 3.10.\n",
      "              warnings.warn(\n",
      "            Running from numpy source directory.\n",
      "            setup.py:480: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates\n",
      "              run_build = parse_setuppy_commands()\n",
      "            Cythonizing sources\n",
      "            Processing numpy/random\\_bounded_integers.pxd.in\n",
      "            Processing numpy/random\\bit_generator.pyx\n",
      "            Processing numpy/random\\mtrand.pyx\n",
      "            Processing numpy/random\\_bounded_integers.pyx.in\n",
      "            Processing numpy/random\\_common.pyx\n",
      "            Processing numpy/random\\_generator.pyx\n",
      "            Processing numpy/random\\_mt19937.pyx\n",
      "            Processing numpy/random\\_pcg64.pyx\n",
      "            Processing numpy/random\\_philox.pyx\n",
      "            Processing numpy/random\\_sfc64.pyx\n",
      "            blas_opt_info:\n",
      "            blas_mkl_info:\n",
      "            No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils\n",
      "            customize MSVCCompiler\n",
      "              libraries mkl_rt not found in ['C:\\\\Users\\\\16695\\\\anaconda3\\\\envs\\\\titanic\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\16695\\\\anaconda3\\\\envs\\\\titanic\\\\libs', 'C:\\\\Users\\\\16695\\\\anaconda3\\\\Library\\\\lib']\n",
      "              NOT AVAILABLE\n",
      "      \n",
      "            blis_info:\n",
      "              libraries blis not found in ['C:\\\\Users\\\\16695\\\\anaconda3\\\\envs\\\\titanic\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\16695\\\\anaconda3\\\\envs\\\\titanic\\\\libs', 'C:\\\\Users\\\\16695\\\\anaconda3\\\\Library\\\\lib']\n",
      "              NOT AVAILABLE\n",
      "      \n",
      "            openblas_info:\n",
      "              libraries openblas not found in ['C:\\\\Users\\\\16695\\\\anaconda3\\\\envs\\\\titanic\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\16695\\\\anaconda3\\\\envs\\\\titanic\\\\libs', 'C:\\\\Users\\\\16695\\\\anaconda3\\\\Library\\\\lib']\n",
      "            get_default_fcompiler: matching types: '['gnu', 'intelv', 'absoft', 'compaqv', 'intelev', 'gnu95', 'g95', 'intelvem', 'intelem', 'flang']'\n",
      "            customize GnuFCompiler\n",
      "            Could not locate executable g77\n",
      "            Could not locate executable f77\n",
      "            customize IntelVisualFCompiler\n",
      "            Could not locate executable ifort\n",
      "            Could not locate executable ifl\n",
      "            customize AbsoftFCompiler\n",
      "            Could not locate executable f90\n",
      "            customize CompaqVisualFCompiler\n",
      "            Could not locate executable DF\n",
      "            customize IntelItaniumVisualFCompiler\n",
      "            Could not locate executable efl\n",
      "            customize Gnu95FCompiler\n",
      "            Could not locate executable gfortran\n",
      "            Could not locate executable f95\n",
      "            customize G95FCompiler\n",
      "            Could not locate executable g95\n",
      "            customize IntelEM64VisualFCompiler\n",
      "            customize IntelEM64TFCompiler\n",
      "            Could not locate executable efort\n",
      "            Could not locate executable efc\n",
      "            customize PGroupFlangCompiler\n",
      "            Could not locate executable flang\n",
      "            don't know how to compile Fortran code on platform 'nt'\n",
      "              NOT AVAILABLE\n",
      "      \n",
      "            atlas_3_10_blas_threads_info:\n",
      "            Setting PTATLAS=ATLAS\n",
      "              libraries tatlas not found in ['C:\\\\Users\\\\16695\\\\anaconda3\\\\envs\\\\titanic\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\16695\\\\anaconda3\\\\envs\\\\titanic\\\\libs', 'C:\\\\Users\\\\16695\\\\anaconda3\\\\Library\\\\lib']\n",
      "              NOT AVAILABLE\n",
      "      \n",
      "            atlas_3_10_blas_info:\n",
      "              libraries satlas not found in ['C:\\\\Users\\\\16695\\\\anaconda3\\\\envs\\\\titanic\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\16695\\\\anaconda3\\\\envs\\\\titanic\\\\libs', 'C:\\\\Users\\\\16695\\\\anaconda3\\\\Library\\\\lib']\n",
      "              NOT AVAILABLE\n",
      "      \n",
      "            atlas_blas_threads_info:\n",
      "            Setting PTATLAS=ATLAS\n",
      "              libraries ptf77blas,ptcblas,atlas not found in ['C:\\\\Users\\\\16695\\\\anaconda3\\\\envs\\\\titanic\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\16695\\\\anaconda3\\\\envs\\\\titanic\\\\libs', 'C:\\\\Users\\\\16695\\\\anaconda3\\\\Library\\\\lib']\n",
      "              NOT AVAILABLE\n",
      "      \n",
      "            atlas_blas_info:\n",
      "              libraries f77blas,cblas,atlas not found in ['C:\\\\Users\\\\16695\\\\anaconda3\\\\envs\\\\titanic\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\16695\\\\anaconda3\\\\envs\\\\titanic\\\\libs', 'C:\\\\Users\\\\16695\\\\anaconda3\\\\Library\\\\lib']\n",
      "              NOT AVAILABLE\n",
      "      \n",
      "            accelerate_info:\n",
      "              NOT AVAILABLE\n",
      "      \n",
      "            C:\\Users\\16695\\AppData\\Local\\Temp\\pip-install-3g481miv\\numpy_aa54c68dd5ac4c63af5cef85604cf29b\\numpy\\distutils\\system_info.py:1914: UserWarning:\n",
      "                Optimized (vendor) Blas libraries are not found.\n",
      "                Falls back to netlib Blas library which has worse performance.\n",
      "                A better performance should be easily gained by switching\n",
      "                Blas library.\n",
      "              if self._calc_info(blas):\n",
      "            blas_info:\n",
      "              libraries blas not found in ['C:\\\\Users\\\\16695\\\\anaconda3\\\\envs\\\\titanic\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\16695\\\\anaconda3\\\\envs\\\\titanic\\\\libs', 'C:\\\\Users\\\\16695\\\\anaconda3\\\\Library\\\\lib']\n",
      "              NOT AVAILABLE\n",
      "      \n",
      "            C:\\Users\\16695\\AppData\\Local\\Temp\\pip-install-3g481miv\\numpy_aa54c68dd5ac4c63af5cef85604cf29b\\numpy\\distutils\\system_info.py:1914: UserWarning:\n",
      "                Blas (http://www.netlib.org/blas/) libraries not found.\n",
      "                Directories to search for the libraries can be specified in the\n",
      "                numpy/distutils/site.cfg file (section [blas]) or by setting\n",
      "                the BLAS environment variable.\n",
      "              if self._calc_info(blas):\n",
      "            blas_src_info:\n",
      "              NOT AVAILABLE\n",
      "      \n",
      "            C:\\Users\\16695\\AppData\\Local\\Temp\\pip-install-3g481miv\\numpy_aa54c68dd5ac4c63af5cef85604cf29b\\numpy\\distutils\\system_info.py:1914: UserWarning:\n",
      "                Blas (http://www.netlib.org/blas/) sources not found.\n",
      "                Directories to search for the sources can be specified in the\n",
      "                numpy/distutils/site.cfg file (section [blas_src]) or by setting\n",
      "                the BLAS_SRC environment variable.\n",
      "              if self._calc_info(blas):\n",
      "              NOT AVAILABLE\n",
      "      \n",
      "            non-existing path in 'numpy\\\\distutils': 'site.cfg'\n",
      "            lapack_opt_info:\n",
      "            lapack_mkl_info:\n",
      "              libraries mkl_rt not found in ['C:\\\\Users\\\\16695\\\\anaconda3\\\\envs\\\\titanic\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\16695\\\\anaconda3\\\\envs\\\\titanic\\\\libs', 'C:\\\\Users\\\\16695\\\\anaconda3\\\\Library\\\\lib']\n",
      "              NOT AVAILABLE\n",
      "      \n",
      "            openblas_lapack_info:\n",
      "              libraries openblas not found in ['C:\\\\Users\\\\16695\\\\anaconda3\\\\envs\\\\titanic\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\16695\\\\anaconda3\\\\envs\\\\titanic\\\\libs', 'C:\\\\Users\\\\16695\\\\anaconda3\\\\Library\\\\lib']\n",
      "              NOT AVAILABLE\n",
      "      \n",
      "            openblas_clapack_info:\n",
      "              libraries openblas,lapack not found in ['C:\\\\Users\\\\16695\\\\anaconda3\\\\envs\\\\titanic\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\16695\\\\anaconda3\\\\envs\\\\titanic\\\\libs', 'C:\\\\Users\\\\16695\\\\anaconda3\\\\Library\\\\lib']\n",
      "              NOT AVAILABLE\n",
      "      \n",
      "            flame_info:\n",
      "              libraries flame not found in ['C:\\\\Users\\\\16695\\\\anaconda3\\\\envs\\\\titanic\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\16695\\\\anaconda3\\\\envs\\\\titanic\\\\libs', 'C:\\\\Users\\\\16695\\\\anaconda3\\\\Library\\\\lib']\n",
      "              NOT AVAILABLE\n",
      "      \n",
      "            atlas_3_10_threads_info:\n",
      "            Setting PTATLAS=ATLAS\n",
      "              libraries lapack_atlas not found in C:\\Users\\16695\\anaconda3\\envs\\titanic\\lib\n",
      "              libraries tatlas,tatlas not found in C:\\Users\\16695\\anaconda3\\envs\\titanic\\lib\n",
      "              libraries lapack_atlas not found in C:\\\n",
      "              libraries tatlas,tatlas not found in C:\\\n",
      "              libraries lapack_atlas not found in C:\\Users\\16695\\anaconda3\\envs\\titanic\\libs\n",
      "              libraries tatlas,tatlas not found in C:\\Users\\16695\\anaconda3\\envs\\titanic\\libs\n",
      "              libraries lapack_atlas not found in C:\\Users\\16695\\anaconda3\\Library\\lib\n",
      "              libraries tatlas,tatlas not found in C:\\Users\\16695\\anaconda3\\Library\\lib\n",
      "            <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>\n",
      "              NOT AVAILABLE\n",
      "      \n",
      "            atlas_3_10_info:\n",
      "              libraries lapack_atlas not found in C:\\Users\\16695\\anaconda3\\envs\\titanic\\lib\n",
      "              libraries satlas,satlas not found in C:\\Users\\16695\\anaconda3\\envs\\titanic\\lib\n",
      "              libraries lapack_atlas not found in C:\\\n",
      "              libraries satlas,satlas not found in C:\\\n",
      "              libraries lapack_atlas not found in C:\\Users\\16695\\anaconda3\\envs\\titanic\\libs\n",
      "              libraries satlas,satlas not found in C:\\Users\\16695\\anaconda3\\envs\\titanic\\libs\n",
      "              libraries lapack_atlas not found in C:\\Users\\16695\\anaconda3\\Library\\lib\n",
      "              libraries satlas,satlas not found in C:\\Users\\16695\\anaconda3\\Library\\lib\n",
      "            <class 'numpy.distutils.system_info.atlas_3_10_info'>\n",
      "              NOT AVAILABLE\n",
      "      \n",
      "            atlas_threads_info:\n",
      "            Setting PTATLAS=ATLAS\n",
      "              libraries lapack_atlas not found in C:\\Users\\16695\\anaconda3\\envs\\titanic\\lib\n",
      "              libraries ptf77blas,ptcblas,atlas not found in C:\\Users\\16695\\anaconda3\\envs\\titanic\\lib\n",
      "              libraries lapack_atlas not found in C:\\\n",
      "              libraries ptf77blas,ptcblas,atlas not found in C:\\\n",
      "              libraries lapack_atlas not found in C:\\Users\\16695\\anaconda3\\envs\\titanic\\libs\n",
      "              libraries ptf77blas,ptcblas,atlas not found in C:\\Users\\16695\\anaconda3\\envs\\titanic\\libs\n",
      "              libraries lapack_atlas not found in C:\\Users\\16695\\anaconda3\\Library\\lib\n",
      "              libraries ptf77blas,ptcblas,atlas not found in C:\\Users\\16695\\anaconda3\\Library\\lib\n",
      "            <class 'numpy.distutils.system_info.atlas_threads_info'>\n",
      "              NOT AVAILABLE\n",
      "      \n",
      "            atlas_info:\n",
      "              libraries lapack_atlas not found in C:\\Users\\16695\\anaconda3\\envs\\titanic\\lib\n",
      "              libraries f77blas,cblas,atlas not found in C:\\Users\\16695\\anaconda3\\envs\\titanic\\lib\n",
      "              libraries lapack_atlas not found in C:\\\n",
      "              libraries f77blas,cblas,atlas not found in C:\\\n",
      "              libraries lapack_atlas not found in C:\\Users\\16695\\anaconda3\\envs\\titanic\\libs\n",
      "              libraries f77blas,cblas,atlas not found in C:\\Users\\16695\\anaconda3\\envs\\titanic\\libs\n",
      "              libraries lapack_atlas not found in C:\\Users\\16695\\anaconda3\\Library\\lib\n",
      "              libraries f77blas,cblas,atlas not found in C:\\Users\\16695\\anaconda3\\Library\\lib\n",
      "            <class 'numpy.distutils.system_info.atlas_info'>\n",
      "              NOT AVAILABLE\n",
      "      \n",
      "            lapack_info:\n",
      "              libraries lapack not found in ['C:\\\\Users\\\\16695\\\\anaconda3\\\\envs\\\\titanic\\\\lib', 'C:\\\\', 'C:\\\\Users\\\\16695\\\\anaconda3\\\\envs\\\\titanic\\\\libs', 'C:\\\\Users\\\\16695\\\\anaconda3\\\\Library\\\\lib']\n",
      "              NOT AVAILABLE\n",
      "      \n",
      "            C:\\Users\\16695\\AppData\\Local\\Temp\\pip-install-3g481miv\\numpy_aa54c68dd5ac4c63af5cef85604cf29b\\numpy\\distutils\\system_info.py:1748: UserWarning:\n",
      "                Lapack (http://www.netlib.org/lapack/) libraries not found.\n",
      "                Directories to search for the libraries can be specified in the\n",
      "                numpy/distutils/site.cfg file (section [lapack]) or by setting\n",
      "                the LAPACK environment variable.\n",
      "              return getattr(self, '_calc_info_{}'.format(name))()\n",
      "            lapack_src_info:\n",
      "              NOT AVAILABLE\n",
      "      \n",
      "            C:\\Users\\16695\\AppData\\Local\\Temp\\pip-install-3g481miv\\numpy_aa54c68dd5ac4c63af5cef85604cf29b\\numpy\\distutils\\system_info.py:1748: UserWarning:\n",
      "                Lapack (http://www.netlib.org/lapack/) sources not found.\n",
      "                Directories to search for the sources can be specified in the\n",
      "                numpy/distutils/site.cfg file (section [lapack_src]) or by setting\n",
      "                the LAPACK_SRC environment variable.\n",
      "              return getattr(self, '_calc_info_{}'.format(name))()\n",
      "              NOT AVAILABLE\n",
      "      \n",
      "            numpy_linalg_lapack_lite:\n",
      "              FOUND:\n",
      "                language = c\n",
      "                define_macros = [('HAVE_BLAS_ILP64', None), ('BLAS_SYMBOL_SUFFIX', '64_')]\n",
      "      \n",
      "            C:\\Users\\16695\\AppData\\Local\\Temp\\pip-build-env-to9nxwtb\\overlay\\Lib\\site-packages\\setuptools\\_distutils\\dist.py:275: UserWarning: Unknown distribution option: 'define_macros'\n",
      "              warnings.warn(msg)\n",
      "            running dist_info\n",
      "            running build_src\n",
      "            build_src\n",
      "            building py_modules sources\n",
      "            creating build\n",
      "            creating build\\src.win-amd64-3.10\n",
      "            creating build\\src.win-amd64-3.10\\numpy\n",
      "            creating build\\src.win-amd64-3.10\\numpy\\distutils\n",
      "            building library \"npymath\" sources\n",
      "            error: Microsoft Visual C++ 14.0 is required. Get it with \"Build Tools for Visual Studio\": https://visualstudio.microsoft.com/downloads/\n",
      "            [end of output]\n",
      "      \n",
      "        note: This error originates from a subprocess, and is likely not a problem with pip.\n",
      "      error: metadata-generation-failed\n",
      "      \n",
      "      × Encountered error while generating package metadata.\n",
      "      ╰─> See above for output.\n",
      "      \n",
      "      note: This is an issue with the package mentioned above, not pip.\n",
      "      hint: See above for details.\n",
      "      [end of output]\n",
      "  \n",
      "  note: This error originates from a subprocess, and is likely not a problem with pip.\n",
      "error: subprocess-exited-with-error\n",
      "\n",
      "× pip subprocess to install build dependencies did not run successfully.\n",
      "│ exit code: 1\n",
      "╰─> See above for output.\n",
      "\n",
      "note: This error originates from a subprocess, and is likely not a problem with pip.\n"
     ]
    }
   ],
   "source": [
    "!pip install pandas-profiling==3.6.6 pandas==1.3.3 scipy==1.7.1\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "ename": "ModuleNotFoundError",
     "evalue": "No module named 'pandas_profiling'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mModuleNotFoundError\u001b[0m                       Traceback (most recent call last)",
      "\u001b[1;32mc:\\Users\\16695\\Titanic_Kaggle_Competition\\Titanic.ipynb Cell 10\u001b[0m line \u001b[0;36m1\n\u001b[1;32m----> <a href='vscode-notebook-cell:/c%3A/Users/16695/Titanic_Kaggle_Competition/Titanic.ipynb#X12sZmlsZQ%3D%3D?line=0'>1</a>\u001b[0m \u001b[39mimport\u001b[39;00m \u001b[39mpandas_profiling\u001b[39;00m\n\u001b[0;32m      <a href='vscode-notebook-cell:/c%3A/Users/16695/Titanic_Kaggle_Competition/Titanic.ipynb#X12sZmlsZQ%3D%3D?line=1'>2</a>\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39mpandas_profiling\u001b[39;00m \u001b[39mimport\u001b[39;00m ProfileReport\n\u001b[0;32m      <a href='vscode-notebook-cell:/c%3A/Users/16695/Titanic_Kaggle_Competition/Titanic.ipynb#X12sZmlsZQ%3D%3D?line=2'>3</a>\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39mpandas_profiling\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mutils\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mcache\u001b[39;00m \u001b[39mimport\u001b[39;00m cache_file\n",
      "\u001b[1;31mModuleNotFoundError\u001b[0m: No module named 'pandas_profiling'"
     ]
    }
   ],
   "source": [
    "import pandas_profiling\n",
    "from pandas_profiling import ProfileReport\n",
    "from pandas_profiling.utils.cache import cache_file"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "titanic",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.0"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
